name: CI workflow

#Event Triggers
on:      # Keyword
  push:  # First Event
    branches: [ "main" ]
  pull_request: # Second Event
    branches: [ "main" ]

# Job
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo python -m pip install --upgrade pip
          sudo pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          sudo flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          sudo flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app